"""Deterministically regenerate the PUBLIC SNAPSHOT demo dataset.

The three-minute competition demo runs against this stable, offline snapshot so
it never depends on live sites during a presentation.

These are REAL public development-application records, captured via a
controlled live sweep (2026-07-19) against six approved public municipal
open-data feeds (see SOURCES below) using the same production acquisition
path as the GUI's "Refresh Development Data" action
(tenderfinder_refresh_service.full_sweep_development_acquirer ->
tenderfinder_raw_sweep.run_connector). They are NOT fictitious.

Sanitization applied before committing:
* Personal applicant names were redacted to "Not available"; only clearly
  corporate/business entity names (Ltd./Inc./Corporation/Development/Design/
  Architecture/etc.) were kept, matching what a public permit register
  typically discloses about the applicant of record.
* No internal notes, no local filesystem paths, no secrets, no contact
  details (email/phone) are present in any field.
* Every ``source_url`` points at the issuing municipality's own public
  portal or open-data file.

Outputs (committed):
* ``development_snapshot.csv``  - the sanitized records.
* ``snapshot_manifest.json``    - capture timestamp, source provenance,
  content hash, per-record expected fit ranges/tier (computed from this
  file's own real, already-observed civil_contractor fit scores, +/-5 to
  tolerate minor future keyword-config revisions), and aggregate acceptance
  values.

Regenerating a FRESH live sample (requires network access to the public
sources below; produces different records since municipal application queues
change over time - this is expected and does not indicate a defect):

    python3 -c "
    import sys; sys.path.insert(0, r'01 Code/CONNECTOR_SWEEP')
    import tenderfinder_refresh_service as rs
    request = rs.RefreshRequest(preset_id='civil_contractor', package_root='.',
                                state_root='/tmp/tf_snapshot_regen',
                                max_records_per_source=200)
    acquirer = rs.make_full_sweep_acquirer(request, package_root='.', run_id='regen')
    result = rs.refresh_development_data(request, acquirer=acquirer,
                                          scorer=rs.make_default_scorer(request))
    print(result.message, result.output_paths)
    "

Then select/sanitize/re-embed a representative subset into this file's
``RECORDS`` list and re-run ``python demo_data/public_snapshot/generate_snapshot.py``.

Run: ``python demo_data/public_snapshot/generate_snapshot.py``
"""
from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent

# Fixed capture timestamp of this real sample (keeps the snapshot reproducible
# - do not use now()).
CAPTURE_TIMESTAMP = "2026-07-19T10:10:47-07:00"
SNAPSHOT_ID = "public_snapshot_2026_07_19_live_sample"

FIELDS = [
    "record_id", "municipality", "app_no", "address", "app_type_stage",
    "status_class", "scope_summary", "applicant_name", "source", "source_url",
]

# Source provenance: the six real public municipal/regional open-data feeds
# this sample was captured from (source_id matches config/sources.csv).
SOURCES = [
    {"source_id": "surrey_devapps_v2", "name": "City of Surrey - Development Applications V2",
     "public_url": "https://citizenportal.surrey.ca/"},
    {"source_id": "surrey_planning_reports", "name": "City of Surrey - Rezoning/DP In-Process Reports",
     "public_url": "https://www.surrey.ca/city-services/2018.aspx"},
    {"source_id": "maple_ridge_devapps", "name": "Maple Ridge - Planning & Development",
     "public_url": "https://geoservices.mapleridge.ca/"},
    {"source_id": "twp_langley_devactivity", "name": "Township of Langley - Development Activity",
     "public_url": "https://www.tol.ca/"},
    {"source_id": "coquitlam_devapps", "name": "Coquitlam - Development Information",
     "public_url": "https://www.coquitlam.ca/"},
    {"source_id": "van_building_permits", "name": "City of Vancouver - Issued Building Permits (Open Data)",
     "public_url": "https://opendata.vancouver.ca/"},
]

# Real, sanitized public development-application records (see module docstring).
RECORDS = [
    {
     'record_id': 'SURREY-26-13067-101-B-AVE',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 13067 101 B Ave',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning one R',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-8964-156-A-ST',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 8964 156 A St',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-6438-192-ST',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 6438 192 St',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-15760-CROY-DON-DR',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 15760 Croy don Dr',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-3090-139-ST',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 3090 139 St',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-13625-112-AVE',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 13625 112 Ave',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-9306-BOTH-WELL-DR',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 9306 Both well Dr',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-3658-160-ST',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 3658 160 St',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-14333-104-AVE',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 14333 104 Ave',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-26-2966-164-ST',
     'municipality': 'Surrey',
     'app_no': '',
     'address': '26 2966 164 St',
     'app_type_stage': 'Rezoning — Rezoning',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from',
     'applicant_name': 'Not available',
     'source': 'surrey_planning_reports',
     'source_url': 'https://www.surrey.ca/sites/default/files/media/documents/RezoningInProcess-Result.pdf',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-15021800',
     'municipality': 'Surrey',
     'app_no': '15-0218-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RA to RF-10 and RF-12; NCP Amendment for changes to the road network  drainage corridors  and to show the proposed multi-use pathway  and Subdivision from two (2) lots into fifteen (15) lots (Five RF-12 lots and ten RF-10) and one (1) remainder lot',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0218',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-15035700',
     'municipality': 'Surrey',
     'app_no': '15-0357-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'NCP Amendment for modification to the local road network; Rezoning from RA to RF-10  RF-12 and RF-13; Development Permit for Hazard Lands and Sensitive Ecosystems; Development Variance Permit to allow subdivision into 27 single family lots.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0357',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-17060100',
     'municipality': 'Surrey',
     'app_no': '17-0601-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RA to RF-13 / NCP Amendment from Low Density Residential 6- 10 u.p.a. to Medium Density\nResidential 10-15 u.p.a. and for changes to the road and drainage networks / to allow subdivision into 20 single family lots.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=17 seq=0601',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-20004000',
     'municipality': 'Surrey',
     'app_no': '20-0040-00',
     'address': '',
     'app_type_stage': 'Conditional Approval',
     'status_class': 'OPEN',
     'scope_summary': 'Rezoning from General Agriculture Zone (A-1) to Comprehensive Development Zone (CD) (based on \nCommunity Commercial Zone (C-8); Local Area Plan (LAP) Amendment from Open Space Corridor/Buffer and Business Park to Commercial; Development Permit; and Subdivision for road dedication to allow the devel',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=20 seq=0040',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-15043500',
     'municipality': 'Surrey',
     'app_no': '15-0435-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RA to RF-13; NCP Amendment from Low Density Residential 6-10 u.p.a. to Medium Density Residential 10-15 u.p.a. and for changes to the road and drainage networks to allow subdivision into nine single family lots.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0435',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-15043900',
     'municipality': 'Surrey',
     'app_no': '15-0439-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RA to RF-13; NCP Amendment from Low Density Residential 6-10 u.p.a. to Medium Density Residential 10-15 u.p.a. and for changes to the road and drainage networks to allow subdivision into nine single family lots.\nSD PLAN CROSS REF 7915-0440-00',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0439',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-15044000',
     'municipality': 'Surrey',
     'app_no': '15-0440-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RA to RF-13; NCP Amendment from Low Density Residential 6-10 u.p.a. to Medium Density Residential 10-15 u.p.a. and for changes to the road and drainage networks to allow subdivision into nine single family lots.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0440',
     "_expected": {'min_fit': 66, 'max_fit': 76, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-19032200',
     'municipality': 'Surrey',
     'app_no': '19-0322-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'LAP Amendment for changes to the road network;  Rezoning from A-1 to IB-3; Development Permit to subdivide into three industrial lots and the development of an 8 361 square metres tilt-up industrial building.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0322',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-19037000',
     'municipality': 'Surrey',
     'app_no': '19-0370-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Rezoning from RF and CD (By-law No. 14112) to CD (based on RM-70); Development Permit to permit the development of a 6-storey apartment building in City Centre. Development Variance Permit to Surety Bond for Servicing Agreement.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0370',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-15011800',
     'municipality': 'Surrey',
     'app_no': '15-0118-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'OCP Amendment for a portion of the site from Urban to Multiple Residential / NCP Amendment for a portion of the site from Townhouse (15 upa) to Townhouse (30 upa) and for modifications to the local road network / Rezoning from RA to RM-30 and CD / Development Permit / Development Variance Permit to',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=15 seq=0118',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'SURREY-19032400',
     'municipality': 'Surrey',
     'app_no': '19-0324-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the minimum front and rear yard setbacks for a lot encumbered by a natural gas transmission (Fortis BC) right-of-way in order to construct a single family dwelling on the lot.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0324',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19032500',
     'municipality': 'Surrey',
     'app_no': '19-0325-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the minimum 400 metre separation distance between a small-scale drug store and an existing drug store.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0325',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19033400',
     'municipality': 'Surrey',
     'app_no': '19-0334-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the front yard and rear yard setback to permit the development of a single-family dwelling.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0334',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19033500',
     'municipality': 'Surrey',
     'app_no': '19-0335-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the rear yard setback of proposed detached garages.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0335',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19033600',
     'municipality': 'Surrey',
     'app_no': '19-0336-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Temporary Use Permit to permit the continued outdoor storage of lumber materials for a period not to exceed three (3) years.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0336',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19034100',
     'municipality': 'Surrey',
     'app_no': '19-0341-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the front yard setback on a lot fronting a cul-de-sac bulb in order to construct a new single family dwelling.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0341',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19034200',
     'municipality': 'Surrey',
     'app_no': '19-0342-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Temporary Use Permit to permit office space and ancillary support services within the existing building on the lot for a child care centre located on the neighbouring lot to the north (9458 - 134 Street)  for a period not to exceed three years.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0342',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19035200',
     'municipality': 'Surrey',
     'app_no': '19-0352-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Amend CD Bylaw No. 18271 to allow an indoor recreational facility as a permitted use.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0352',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19035800',
     'municipality': 'Surrey',
     'app_no': '19-0358-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Development Variance Permit to reduce the front yard and rear yard setbacks to permit the development of a single-family dwelling.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0358',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'SURREY-19035900',
     'municipality': 'Surrey',
     'app_no': '19-0359-00',
     'address': '',
     'app_type_stage': 'Concluded',
     'status_class': 'CLOSED',
     'scope_summary': 'Temporary Use Permit to permit an existing concrete restoration  repair and leveling business to continue to operate in its current location  for a period not to exceed (3) years.',
     'applicant_name': 'Not available',
     'source': 'surrey_devapps_v2',
     'source_url': 'https://citizenportal.surrey.ca/citizenportal/integration/publicProjectForward.html?year=19 seq=0359',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-23127',
     'municipality': 'Coquitlam',
     'app_no': '23-127',
     'address': '564, 568, 574 Harrison Ave & 565, 569, 575 Kemsley Ave ',
     'app_type_stage': 'Conditional Approval',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To construct a six-storey wood-frame condominium building containing 156 residential units over a two-level underground parkade.\n\nApplications associated with proposal:\nRezoning of six lots from RS-1 to RM-3.\nNon-Delegated Development Permit for Form and Character.\nSubdivision Appl',
     'applicant_name': 'Quantum Properties Inc',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'COQUITLAM-21088',
     'municipality': 'Coquitlam',
     'app_no': '21-088',
     'address': '634, 636, 640, 642, 644 Tyndall Street',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct two 6-storey residential buildings with 120 units.\n\nApplication Associated with Proposal:\nNon-Delegated Development Permit for Form and Character\nRezoning from RS-1 to RM-3.\nSubdivision for site configuration.',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'COQUITLAM-19092',
     'municipality': 'Coquitlam',
     'app_no': '19-092',
     'address': '200 Marmont St.,1053, 1055, 1057, 1059 James Ave.',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Proposal: To construct a six storey residential building with 74 residential units and variance to reduce eastern setback from 4.0m to 3.5m.\n\nApplications associated with proposal:\nRezoning 4 lots from RS-1 to RM-3\nDevelopment Permit for form and character and variance. \nSubdivision to create 1 RM-3',
     'applicant_name': '1164614 BC Ltd.',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'COQUITLAM-21188',
     'municipality': 'Coquitlam',
     'app_no': '21-188',
     'address': '567, 599, 601 Lougheed Hwy, 605, 609, 611 Edgar Ave, 350, 366 Guilby St',
     'app_type_stage': 'Conditional Approval',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct three 6-storey residential buildings with a total of 307 market rental units over 2 levels of underground parking.\n\nApplications Associated with Proposal:\nRezoning eight lots from RS-1 to RM-3\nNon-Delegated Development Permit for Form and Character\nSubdivision for lot',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'COQUITLAM-20020',
     'municipality': 'Coquitlam',
     'app_no': '20-020',
     'address': '963 & 973 Edgar Ave',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct a multiplex development with 6 residential units in 2 buildings\n\nApplications associated with proposal\nRezoning from RT-1 to RT-3\nDelegated Development Permit for form and character\nSubdivision to create 1 RT-3 lot from 2 RT-1 lot.',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 57, 'max_fit': 67, 'tier': 'HIGH'},
    },
    {
     'record_id': 'COQUITLAM-24007',
     'municipality': 'Coquitlam',
     'app_no': '24-007',
     'address': '708 Farrow St',
     'app_type_stage': 'Conditional Approval',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To create an airspace parcel for the South Tower of Smith & Farrow (market strata vs. rental/non-market housing).\n\nApplications associated with proposal: \nSubdivision application to create an airspace parcel.',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-23097',
     'municipality': 'Coquitlam',
     'app_no': '23-097',
     'address': '910 Westwood Street',
     'app_type_stage': 'Conditional Approval',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To subdivide a RS-1 lot into three and retain a heritage house.\n\nApplications Associated with Proposal:\nHeritage Revitalization Agreement\nSubdivision Application for site configuration',
     'applicant_name': 'Empire Design Corporation',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-24184',
     'municipality': 'Coquitlam',
     'app_no': '24-184',
     'address': '3637 Sheffield Ave',
     'app_type_stage': 'Active Application',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: Phased Strata application to construct 101 townhome units in 4 phases. \n\nApplications associated with proposal: \nSubdivision application for Phased Development.',
     'applicant_name': 'Polygon Ridgewood Development Ltd. ',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-18130',
     'municipality': 'Coquitlam',
     'app_no': '18-130',
     'address': '269 King St',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To construct a Triplex.\n\nApplications associated with proposal:\nDevelopment Permit for form and character.',
     'applicant_name': 'Rail House Builders Inc.',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-25101',
     'municipality': 'Coquitlam',
     'app_no': '25-101',
     'address': '931 Stewart Avenue',
     'app_type_stage': 'Active Application',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct a triplex\n\nAssociated application to proposal:\nDelegated Development Permit for form and character',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'COQUITLAM-23078',
     'municipality': 'Coquitlam',
     'app_no': '23-078',
     'address': '1144 Inlet St',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To construct five 6-storey apartment buildings with 474 affordable rental units across two phases. To rezone and subdivide one lot from RT-2 and RM-1 to two RM-3 lots. \n\nApplications associated with proposal:\nRezoning 1 lot from RT-2 and RM-1 to RM-3.\nSubdivision to create 2 RM-3 l',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'COQUITLAM-22099',
     'municipality': 'Coquitlam',
     'app_no': '22-099',
     'address': '1107 & 1113 Quadling Ave',
     'app_type_stage': 'Active Application',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct at 14 unit Multiplex residential building. \n\nApplications associated with proposal: \nNon-delegated development permit for form and character.\nRezoning 2 lots from RT-1 to RT-3\nLot consolidation of 2 RT-1 lots into 1 RT-3 lot.',
     'applicant_name': 'Mara & Natha Architecture Ltd.',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'COQUITLAM-25002',
     'municipality': 'Coquitlam',
     'app_no': '25-002',
     'address': '230 Allard Street',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct a duplex \n\nApplications associated with proposal:\nDelegated development permit form and character\nSubdivision for site configuration',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'COQUITLAM-24094',
     'municipality': 'Coquitlam',
     'app_no': '24-094',
     'address': '602 Sydney Avenue',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: To construct a six-story senior rental housing apartment building with underground parking, comprising 116 units.\n\nApplications associated with Proposal:\nNon-Delegated Development Permit for Form and Character\nSubdivision Application for site configuration.',
     'applicant_name': 'Integra Architecture Inc.',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'COQUITLAM-21025',
     'municipality': 'Coquitlam',
     'app_no': '21-025',
     'address': '314 Nelson St',
     'app_type_stage': 'Approved',
     'status_class': 'OPEN',
     'scope_summary': 'Project Proposal: to construct a fourplex.\n\nApplications associated with proposal: \nDelegated Development Permit for Form and Character\nSubdivision for final lot configuration',
     'applicant_name': 'Not available',
     'source': 'coquitlam_devapps',
     'source_url': 'https://services2.arcgis.com/Q6Lq3evZUGfPrN7o/arcgis/rest/services/Development_Information_Demo/FeatureServer/0',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'VANCOUVER-BP202104012',
     'municipality': 'Vancouver',
     'app_no': 'BP-2021-04012',
     'address': '2628 DUKE STREET, Vancouver, BC V5R 4S9',
     'app_type_stage': 'New Building',
     'status_class': 'OPEN',
     'scope_summary': 'Certified Professional Program - New Building - To construct a 4 storey, 29 dwelling units, secured market rental, multiple dwelling (with one lock-off) with amenity over 1 level of underground parking with vehicular access from the rear lane.\n\nVBBL 2019 - NFPA 13/13R.\n\nSTAGE 1 - Excavation, Sho',
     'applicant_name': 'LMDG Building Code Consultants Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-BP202301817',
     'municipality': 'Vancouver',
     'app_no': 'BP-2023-01817',
     'address': '2791 W 21ST AVENUE, Vancouver, BC V6L 1K4',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Low Density Housing - Demolition / Deconstruction - To demolish the existing one family dwelling building ($15,000) on this site by means of deconstruction.\n\nGreen Demolition Conditions Apply : 75% Recycling Rate of Building Materials Required\n\nDemo Declaration – Bhullar Excavating and Demolitio',
     'applicant_name': 'Absolute Design Services',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-BP202204092',
     'municipality': 'Vancouver',
     'app_no': 'BP-2022-04092',
     'address': '3538 W 14TH AVENUE, Vancouver, BC V6R 2W4',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Low Density Housing - Demolition / Deconstruction - Building Permit for DB-2022-02604 2.5 FD (LOT A)\n\nGreen demo - recycle and reuse 90% \n\nDemo contractor: Bill Jatana- R B Excavating 2000 Ltd.\n                  Tele: 604-327-6337\n\n***This permit is issued under the VBBL 2019, with updated en',
     'applicant_name': 'Aneek Developments Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-BP202104170',
     'municipality': 'Vancouver',
     'app_no': 'BP-2021-04170',
     'address': '5092 WALDEN STREET, Vancouver, BC V5W 2V7',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Low Density Housing - Demolition / Deconstruction - To demolish the existing one family dwelling building ($15,000) on this site by means of deconstruction.\n\nDemo Declaration – AKAL DEMOLITION & EXCAVATING LTD  (778)-318-1373\n\nThis permit is subject to the Green Demolition Bylaw (11023)\n\nPre-1',
     'applicant_name': 'Aneek Developments Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-DB202401881',
     'municipality': 'Vancouver',
     'app_no': 'DB-2024-01881',
     'address': '5969 GRANVILLE STREET, Vancouver, BC V6M 3C9',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Enquiry Centre - Demolition / Deconstruction - To demolish to grade this existing Single Detached House (1993) on this site.\n\nDemolition Contractor: Zack Dhillon of Power Excavating Ltd\n\nRelated to:\nDP-2024-00034: Issued\nBP-2024-01654: In Review\nBP-2024-01655: In Review\nBP-2024-01656: In Rev',
     'applicant_name': 'Aneek Developments Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-DB202404337',
     'municipality': 'Vancouver',
     'app_no': 'DB-2024-04337',
     'address': '2976 W 13TH AVENUE, Vancouver, BC V6K 2T9',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Enquiry Centre - Demolition / Deconstruction - To demolish to grade this Single Detached House (1928) and its accessory building on the site. No Excavation or shoring work is permitted. 75% of the demolition material must be recycled. \n\nNote: \n1) Notice of Demolition must be provided to District',
     'applicant_name': 'Aneek Developments Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-DB202502486',
     'municipality': 'Vancouver',
     'app_no': 'DB-2025-02486',
     'address': '240 E 20TH AVENUE, Vancouver, BC V5V 1M1',
     'app_type_stage': 'Demolition / Deconstruction',
     'status_class': 'OPEN',
     'scope_summary': 'Low Density Housing - Demolition / Deconstruction - To demolish the existing one family dwelling building ($40,000) on this site.\n\nDemo Declaration – Bhullar Excavating & Demolition Inc. (Baghail Bhullar)   (778)-891-4556',
     'applicant_name': 'Aneek Developments Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'VANCOUVER-BP202302802',
     'municipality': 'Vancouver',
     'app_no': 'BP-2023-02802',
     'address': '2055 E BROADWAY, Vancouver, BC V5N 1W6',
     'app_type_stage': 'New Building',
     'status_class': 'OPEN',
     'scope_summary': 'Certified Professional Program - New Building - To construct  a new 6-storey wood frame strata condominium building containing 64 units, all over 2 levels of underground parking.\n\n17-Jan-2025 - Stage 1 (excavation & shoring) issued. \n02-May-2025 - BP Rev#1(extended excavation) issued.\n20-June-20',
     'applicant_name': 'LMDG Building Code Consultants Ltd.',
     'source': 'van_building_permits',
     'source_url': 'issued-building-permits',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-622750',
     'municipality': 'Maple Ridge',
     'app_no': '622750',
     'address': 'SELKIRK AVE',
     'app_type_stage': 'Development Permit — New',
     'status_class': 'OPEN',
     'scope_summary': 'Multi-Family',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-621970',
     'municipality': 'Maple Ridge',
     'app_no': '621970',
     'address': '123 AVE',
     'app_type_stage': 'Development Permit — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Natural Features',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-621311',
     'municipality': 'Maple Ridge',
     'app_no': '621311',
     'address': '101A AVE',
     'app_type_stage': 'Rezoning — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Single Family',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-620051',
     'municipality': 'Maple Ridge',
     'app_no': '620051',
     'address': 'ANSELL ST',
     'app_type_stage': 'Development Permit — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Natural Features',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-619217',
     'municipality': 'Maple Ridge',
     'app_no': '619217',
     'address': '203 ST',
     'app_type_stage': 'Development Permit — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Watercourse Protection',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-619203',
     'municipality': 'Maple Ridge',
     'app_no': '619203',
     'address': '112 AVE',
     'app_type_stage': 'Development Permit — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Watercourse Protection',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-618775',
     'municipality': 'Maple Ridge',
     'app_no': '618775',
     'address': 'LAITY ST',
     'app_type_stage': 'Rezoning — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Text Amendment',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-621959',
     'municipality': 'Maple Ridge',
     'app_no': '621959',
     'address': 'DEWDNEY TRUNK RD',
     'app_type_stage': 'Pre-Application Review — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-621161',
     'municipality': 'Maple Ridge',
     'app_no': '621161',
     'address': '249 ST',
     'app_type_stage': 'Pre-Application Review — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-620388',
     'municipality': 'Maple Ridge',
     'app_no': '620388',
     'address': '272 ST',
     'app_type_stage': 'Variance Permit — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-620162',
     'municipality': 'Maple Ridge',
     'app_no': '620162',
     'address': '122 AVE',
     'app_type_stage': 'Pre-Application Review — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-619362',
     'municipality': 'Maple Ridge',
     'app_no': '619362',
     'address': 'LOUGHEED HWY',
     'app_type_stage': 'Soil Deposit Permit — Pending Review',
     'status_class': 'OPEN',
     'scope_summary': 'Non ALR',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-618644',
     'municipality': 'Maple Ridge',
     'app_no': '618644',
     'address': 'LOUGHEED HWY',
     'app_type_stage': 'Pre-Application Review — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'MAPLE-RIDGE-618631',
     'municipality': 'Maple Ridge',
     'app_no': '618631',
     'address': '232 ST',
     'app_type_stage': 'Pre-Application Review — In Progress',
     'status_class': 'OPEN',
     'scope_summary': 'Application is in review stage.',
     'applicant_name': 'Not available',
     'source': 'maple_ridge_devapps',
     'source_url': 'https://geoservices.mapleridge.ca/server/rest/services/DataCatalog/PlanningDevelopment/MapServer/1',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RZ100681',
     'municipality': 'Township of Langley',
     'app_no': 'RZ100681',
     'address': '4567 215 Street',
     'app_type_stage': 'COUNCIL 3RD READING — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes to rezone property from Suburban Residential Zone SR-1 to Residential Zone R-1E for the development of a four (4) lot single family residential subdivision.  A Subdivision application and a Development Variance Permit application to reduce the minimum lot frontage requirement',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RZ100681',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RZ100790',
     'municipality': 'Township of Langley',
     'app_no': 'RZ100790',
     'address': '7410 and 7438 208 Street,7423, 7428 and 7446 209A Street and road closures',
     'app_type_stage': 'COUNCIL 1 & 2 READINGS — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes to rezone property from Suburban Residential Zone (SR-2) to Comprehensive Development Zone (CD) to accommodate apartment use (2.4 FSR) and rowhouse/townhouse use (up to 22 UPA) consistent with the Smith Neighbourhood Plan.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RZ100790',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101489',
     'municipality': 'Township of Langley',
     'app_no': 'DP101489',
     'address': '20577, 20593, 20605, & 20565 74B Avenue and 20572, 20560, 20596, & 20608 76 Avenue',
     'app_type_stage': 'DELEGATE ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant has applied for a form and character development permit for the purpose of constructing 66 townhouse units.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101489',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-SA101397',
     'municipality': 'Township of Langley',
     'app_no': 'SA101397',
     'address': '4343 216 Street',
     'app_type_stage': 'DECISION LETTER — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes a Homesite Severance subdivision under Section 21 (2) of the ALC Act. Existing zoning is Rural Zone RU-10. The Provincial Agricultural Land Commission approval was granted on March 20, 2025.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=SA101397',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101521',
     'municipality': 'Township of Langley',
     'app_no': 'DP101521',
     'address': '19791 101 Avenue',
     'app_type_stage': 'COUNCIL ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant has applied for a streamside development permit for the purpose of constructing an industrial building.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101521',
     "_expected": {'min_fit': 39, 'max_fit': 49, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RO100301',
     'municipality': 'Township of Langley',
     'app_no': 'RO100301',
     'address': '7290 & 7320 208 Street',
     'app_type_stage': 'PUBLIC HEARING — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes to amend the Smith Neighbourhood Plan and rezone property from Suburban Residential Zone (SR-2)  to Comprehensive Development Zone for the development of 22 townhouses & 225 apartment units.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RO100301',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RZ100711',
     'municipality': 'Township of Langley',
     'app_no': 'RZ100711',
     'address': '19942 78B Avenue',
     'app_type_stage': 'COUNCIL 3RD READING — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'Application to rezone approximately 0.9 ha (2.23 ac) of land located at 19942 – 78B Avenue to Comprehensive Development Zone CD-216 to facilitate development of approximately 79 apartments, 133 hotel rooms and approximately 1,844.37 m² (19,852.58 ft²) of ground floor commercial space. Development pe',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RZ100711',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RO100324',
     'municipality': 'Township of Langley',
     'app_no': 'RO100324',
     'address': '7518 and 7540 208 Street',
     'app_type_stage': 'COUNCIL 1 & 2 READINGS — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': "The applicant proposes to amend the Smith Neighbourhood Plan by increasing the FSR of the building from 2.4 to 3.25 and rezone property for the development of a 6-storey seniors' housing consisting of 211 apartment units.  The applicant further proposes a lot line adjustment with the southern portio",
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RO100324',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101462',
     'municipality': 'Township of Langley',
     'app_no': 'DP101462',
     'address': '7290 & 7320 208 Street',
     'app_type_stage': 'HEARING — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes to amend the Smith Neighbourhood Plan and rezone property from Suburban Residential Zone (SR-2)  to Comprehensive Development Zone for the development of 22 townhouses & 225 apartment units.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101462',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-SA101399',
     'municipality': 'Township of Langley',
     'app_no': 'SA101399',
     'address': '2600 Block of 268 Street',
     'app_type_stage': 'DECISION LETTER — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The Applicant proposes to amend the Aldergrove Community Plan and rezone property from Suburban Residential Zone (SR-2) to a Comprehensive Development Zone (CD), Residential Compact Lot R-CL(A) and Residential Zone (R-1A) for the development of 45 townhouse units and 25 single family lots.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=SA101399',
     "_expected": {'min_fit': 30, 'max_fit': 40, 'tier': 'LOW'},
    },
    {
     'record_id': 'TWP-LANGLEY-RZ100532',
     'municipality': 'Township of Langley',
     'app_no': 'RZ100532',
     'address': '7042 and 7058 204 Street',
     'app_type_stage': 'COUNCIL FINAL READING — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The Applicant proposes to rezone property from Suburban Residential Zone (SR-2)  to a Comprehensive Development Zone yet to be determined for the development of 37 townhouse units.  Development Permit and Subdivision applications have also been submitted.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=RZ100532',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101013',
     'municipality': 'Township of Langley',
     'app_no': 'DP101013',
     'address': '7042 and 7058 204 Street',
     'app_type_stage': 'COUNCIL ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The Applicant proposes to rezone property from Suburban Residential Zone (SR-2)  to a Comprehensive Development Zone yet to be determined for the development of 37 townhouse units.  Development Permit and Subdivision applications have also been submitted.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101013',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101443',
     'municipality': 'Township of Langley',
     'app_no': 'DP101443',
     'address': '9494 200 Street',
     'app_type_stage': 'COUNCIL ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant has applied for a form and character development permit for the purpose of constructing a new industrial building. Development variance permit and subdivision applications have also been submitted. Existing zoning is Service Industrial Zone M-1A.',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101443',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101508',
     'municipality': 'Township of Langley',
     'app_no': 'DP101508',
     'address': '3650 203A Street',
     'app_type_stage': 'COUNCIL ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The applicant proposes to vary the minimum lot size from 930 m2 to 894.1 m2 on one portion of the lot, for the development of a 2-lot single family residential subdivision.  Existing zoning is Residential Zone R-1E. A subdivision and Development Permit application for Neighbourhood Forest Fire Hazar',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101508',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
    {
     'record_id': 'TWP-LANGLEY-DP101374',
     'municipality': 'Township of Langley',
     'app_no': 'DP101374',
     'address': '20545 76 Avenue',
     'app_type_stage': 'DELEGATE ISSUANCE — ACTIVE',
     'status_class': 'OPEN',
     'scope_summary': 'The Applicant proposes to rezone property from Suburban Residential Zone (SR-2) to Residential Zone R-1A and Residential Compact Lot Zones R-CL(A), R-CL(B), R-CL(RH) and R-CL(SD) for the development of a 23 unit mixed residential development.  Subdivision and Development Permit applications have als',
     'applicant_name': 'Not available',
     'source': 'twp_langley_devactivity',
     'source_url': 'https://e-connect.tol.ca/OurCity/Prospero/Details.aspx?folderNumber=DP101374',
     "_expected": {'min_fit': 48, 'max_fit': 58, 'tier': 'MEDIUM'},
    },
]


def _write_csv(path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=FIELDS)
        writer.writeheader()
        for record in RECORDS:
            writer.writerow({field: record[field] for field in FIELDS})


def _content_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> int:
    csv_path = HERE / "development_snapshot.csv"
    _write_csv(csv_path)
    ge60 = sum(1 for record in RECORDS if record["_expected"]["tier"] == "HIGH")
    manifest = {
        "schema_version": 1,
        "snapshot_id": SNAPSHOT_ID,
        "data_mode": "PUBLIC_SNAPSHOT",
        "capture_timestamp": CAPTURE_TIMESTAMP,
        "dataset_file": csv_path.name,
        "content_hash": _content_hash(csv_path),
        "record_count": len(RECORDS),
        "sanitization": (
            "Real public development-application records captured via a controlled "
            "live sweep against approved public municipal open-data feeds. Personal "
            "applicant names redacted to 'Not available'; only corporate/business "
            "entity names retained. No internal notes, local paths, secrets, or "
            "contact details."
        ),
        "source_provenance": SOURCES,
        "acceptance": {
            "preset_id": "civil_contractor",
            "min_records_fit_ge_60": ge60,
            "per_record": {
                record["record_id"]: record["_expected"] for record in RECORDS
            },
        },
    }
    (HERE / "snapshot_manifest.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"Wrote {len(RECORDS)} snapshot records + manifest to {HERE}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
